# Лабораторная работа №1
## Выполнил студент группы БВТ1902 Власов Глеб

In [11]:
import random
import pandas as pd
import statistics
import numpy as np
import queue as pq
import heapq

### Задание 2
### Генератор матриц

In [9]:
# Предобработка:
def gen_matrix(m=50, n=50, min_limit=-250, max_limit=1000) -> list:
    matrix = pd.DataFrame([[random.randint(min_limit, max_limit) for j in range(n)] for i in range(m)])
    
    return matrix

In [12]:
# Формирование матрицы
test = gen_matrix(10, 10)
test

     0    1    2    3    4    5    6    7    8    9
0 -173  115  424  616  586  -87   -7  606  672  397
1  380  164  414  413  851  485  383  258  244  375
2  428  551  -89  666  830  829  -56 -243 -161  933
3   46  579    8  269  792  924  394  288  546  106
4  462  133  563 -175  872  927  759  911    7  837
5  632  801  103  838  440  270  -79  -38 -207  -58
6  240  808  -87  378  889   65 -232  -48   50  532
7  476  473 -106  867   76  757 -143  440  576  918
8  181  161  400  804  677  931  957  504  725  -87
9  912  348  156  823  476  746  364  643  227  470

### Задание 3

### Сортировка строк матриц

In [15]:
# Предобработка

## QUICKSORT
def quick_sorted(matrix_str) -> list:
    if len(matrix_str) <= 1:
        return matrix_str
    else:
        med = statistics.median(matrix_str)
        lower_nums = [j for j in matrix_str if j < med]
        equal_nums = [j for j in matrix_str if j == med]
        bigger_nums = [j for j in matrix_str if j > med]
        
    return quick_sorted(lower_nums) + equal_nums + quick_sorted(bigger_nums)


def quick_sort(matrix) -> list:
    for it in range(len(matrix)):
        matrix.iloc[it] = quick_sorted(matrix.iloc[it])
        
    return matrix


## BUBBLESORT
def bubble_sorted(matrix_str) -> list:
    length = len(matrix_str)
    
    for it in range(length):
        changes = False
        for j in range(0, length-it-1):
            if matrix_str[j] > matrix_str[j+1]:
                matrix_str[j], matrix_str[j+1] = matrix_str[j+1], matrix_str[j]
                changes = True
                
        if changes == False:
            return matrix_str
            
            
def bubble_sort(matrix) -> list:
    for it in range(len(matrix)):
        matrix.iloc[it] = bubble_sorted(matrix.iloc[it])
        
    return matrix
        
        
## SELECTIONSORT
def selection_sorted(matrix_str) -> list:
    length = len(matrix_str)
    
    for it in range(length):
        index = it
        for j in range(it+1, length):
            if matrix_str[j] < matrix_str[index]:
                index = j
        matrix_str[it], matrix_str[index] = matrix_str[index], matrix_str[it]
    return matrix_str
            

def selection_sort(matrix) -> list:
    for it in range(len(matrix)):
            matrix.iloc[it] = selection_sorted(matrix.iloc[it])   
            
    return matrix
    

## INSERTIONSORT
def insertion_sorted(matrix_str) -> list:
    matrix_str = list(matrix_str)
    
    for it, n in enumerate(matrix_str):
        ins_pos = 0
        for j, m in reversed([num for num in enumerate(matrix_str[:it])]):
            if m < n:
                ins_pos = j + 1
                break
        matrix_str.insert(ins_pos, matrix_str.pop(it))
                
    return matrix_str


def insertion_sort(matrix) -> list:
    for it in range(len(matrix)):
            matrix.iloc[it] = insertion_sorted(matrix.iloc[it])  
            
    return matrix


## SHELLSORT #non optimized version???
def shell_sorted(matrix_str) -> list:
    length = len(matrix_str)
    gap = length 
    
    while gap > 0:
        for it in range(gap, length):
            buff = matrix_str[it]
            j = it
            while j >= gap and matrix_str[j-gap] > buff:
                matrix_str[j] = matrix_str[j-gap]
                j -= gap
            matrix_str[j] = buff
        gap //= 2
    
    return matrix_str


def shell_sort(matrix) -> list:
    for it in range(len(matrix)):
            matrix.iloc[it] = shell_sorted(matrix.iloc[it])  
            
    return matrix

## HEAPSORT
def heapify(matrix_str) -> list:
    for it in reversed(range(1, len(matrix_str))):
        parent = (it - 1)//2
        if matrix_str[parent] > matrix_str[it]:
            matrix_str[parent], matrix_str[it] = matrix_str[it], matrix_str[parent]
            
            
def heap_sorted(it) -> list:
    result = []
    matrix_str = list(it)
    
    while matrix_str:
        heapify(matrix_str)
        result.append(matrix_str.pop(0))
        
    return result


def heap_sort(matrix) -> list:
    for it in range(len(matrix)):
        matrix.iloc[it] = heap_sorted(matrix.iloc[it])
        
    return matrix

In [16]:
# Делаю копии матриц для проверки
test_sort_quick = test.copy()
test_sort_bubble = test.copy()
test_sort_selection = test.copy()
test_sort_insertion = test.copy()
test_sort_shell = test.copy()
test_sort_tournament = test.copy()
test_sort_heap = test.copy()

In [17]:
%%time 
quick_sort(test_sort_quick)
test_sort_quick

CPU times: user 4.84 ms, sys: 161 µs, total: 5 ms
Wall time: 4.96 ms

     0    1    2    3    4    5    6    7    8    9
0 -173  -87   -7  115  397  424  586  606  616  672
1  164  244  258  375  380  383  413  414  485  851
2 -243 -161  -89  -56  428  551  666  829  830  933
3    8   46  106  269  288  394  546  579  792  924
4 -175    7  133  462  563  759  837  872  911  927
5 -207  -79  -58  -38  103  270  440  632  801  838
6 -232  -87  -48   50   65  240  378  532  808  889
7 -143 -106   76  440  473  476  576  757  867  918
8  -87  161  181  400  504  677  725  804  931  957
9  156  227  348  364  470  476  643  746  823  912

In [18]:
%%time 
bubble_sort(test_sort_bubble)
test_sort_bubble

CPU times: user 19.5 ms, sys: 447 µs, total: 20 ms
Wall time: 19.7 ms

     0    1    2    3    4    5    6    7    8    9
0 -173  -87   -7  115  397  424  586  606  616  672
1  164  244  258  375  380  383  413  414  485  851
2 -243 -161  -89  -56  428  551  666  829  830  933
3    8   46  106  269  288  394  546  579  792  924
4 -175    7  133  462  563  759  837  872  911  927
5 -207  -79  -58  -38  103  270  440  632  801  838
6 -232  -87  -48   50   65  240  378  532  808  889
7 -143 -106   76  440  473  476  576  757  867  918
8  -87  161  181  400  504  677  725  804  931  957
9  156  227  348  364  470  476  643  746  823  912

In [19]:
%%time 
selection_sort(test_sort_selection)
test_sort_selection
# arr = [3,1,2,5]
# selection_sorted(arr)
# arr

CPU times: user 13.8 ms, sys: 365 µs, total: 14.1 ms
Wall time: 13.9 ms

     0    1    2    3    4    5    6    7    8    9
0 -173  -87   -7  115  397  424  586  606  616  672
1  164  244  258  375  380  383  413  414  485  851
2 -243 -161  -89  -56  428  551  666  829  830  933
3    8   46  106  269  288  394  546  579  792  924
4 -175    7  133  462  563  759  837  872  911  927
5 -207  -79  -58  -38  103  270  440  632  801  838
6 -232  -87  -48   50   65  240  378  532  808  889
7 -143 -106   76  440  473  476  576  757  867  918
8  -87  161  181  400  504  677  725  804  931  957
9  156  227  348  364  470  476  643  746  823  912

In [20]:
%%time 
insertion_sort(test_sort_insertion)
test_sort_insertion

CPU times: user 2.25 ms, sys: 0 ns, total: 2.25 ms
Wall time: 2.26 ms

     0    1    2    3    4    5    6    7    8    9
0 -173  -87   -7  115  397  424  586  606  616  672
1  164  244  258  375  380  383  413  414  485  851
2 -243 -161  -89  -56  428  551  666  829  830  933
3    8   46  106  269  288  394  546  579  792  924
4 -175    7  133  462  563  759  837  872  911  927
5 -207  -79  -58  -38  103  270  440  632  801  838
6 -232  -87  -48   50   65  240  378  532  808  889
7 -143 -106   76  440  473  476  576  757  867  918
8  -87  161  181  400  504  677  725  804  931  957
9  156  227  348  364  470  476  643  746  823  912

In [10]:
%%time 
shell_sort(test_sort_shell)
test_sort_shell
# arr = [3,1,2,5]

Wall time: 10.9 ms

     0    1    2    3    4    5    6    7    8     9
0 -196 -122  -41  -35   64  422  734  784  909   985
1 -184 -128  204  234  537  752  865  929  932   950
2 -246   97  124  359  445  555  714  774  777   884
3 -170  -94  -80   45  155  162  219  489  770   879
4 -198    2  269  334  383  699  818  839  854   996
5 -240 -156  -61  197  198  477  557  611  737   742
6 -134   19   35  299  335  343  497  835  893  1000
7  -27   59  144  197  254  376  637  752  802   867
8 -203 -168  493  504  606  611  697  794  925   982
9  112  199  314  332  341  532  557  698  768   923

In [21]:
%%time 
heap_sort(test_sort_heap)
test_sort_heap

CPU times: user 5.26 ms, sys: 767 µs, total: 6.03 ms
Wall time: 5.35 ms

     0    1    2    3    4    5    6    7    8    9
0 -173  -87   -7  115  397  424  586  606  616  672
1  164  244  258  375  380  383  413  414  485  851
2 -243 -161  -89  -56  428  551  666  829  830  933
3    8   46  106  269  288  394  546  579  792  924
4 -175    7  133  462  563  759  837  872  911  927
5 -207  -79  -58  -38  103  270  440  632  801  838
6 -232  -87  -48   50   65  240  378  532  808  889
7 -143 -106   76  440  473  476  576  757  867  918
8  -87  161  181  400  504  677  725  804  931  957
9  156  227  348  364  470  476  643  746  823  912

# ЗАДАЧИ

## Задача 1. «Треугольник с максимальным периметром»

In [22]:
def triangle(arr) -> int:
    maxP = 0
    length = len(arr)
    arr = list(reversed(heap_sorted(arr)))
    
    for i in range(0, length-2):
        if arr[i] < (arr[i + 1] + arr[i + 2]):
            maxP = max(maxP, arr[i] + arr[i + 1] + arr[i + 2])
            break
    
# Тестовый вариант без отсортированного массива p.s. ну а вдруг
    
#     for i in range(length-2):
#         for j in range(i + 1, length - 1):
#             for k in range(j + 1, length):
#                 a, b, c = arr[i], arr[j], arr[k]
#                 if(a < b + c and b < a + c and c < a + b):
#                     maxP = max(maxP, a + b + c)
    
    
    return maxP

In [23]:
arr = [3,2,3,4]
print(triangle(arr))

10

## Задача 2. «Максимальное число»

In [26]:
def max_value(arr) -> str:
    empty, vals = [], ""
    length = len(str(max(arr))) + 1
    
    for i in arr:
        buff = str(i) * length
        empty.append((buff[:], i))
        
    empty = list(reversed(heap_sorted(empty)))
    
    for i in empty:
        vals += str(i[1])
        
    if int(vals) == 0:
        return "0"
    
    return vals

In [27]:
arr = [3,30,34,5,9]
max_value(arr)

'9534330'

## Задача 3. «Сортировка диагоналей в матрице»

In [30]:
 def diag_sort(matrix) -> list:
        y, x = len(matrix), len(matrix[0])
        for i in range(2-y, x-1):
            valid = range(max(0, 0-i), min(y, x-i))
            diag, k = heap_sorted([matrix[j][i+j] for j in valid]), 0
            for j in valid:
                matrix[j][i+j], k = diag[k], k + 1
        return matrix

In [31]:
mat = [[11, 25, 66, 1, 69, 7], [23, 55, 17, 45, 15, 52], [75, 31, 36,
44, 58, 8], [22, 27, 33, 25, 68, 4], [84, 28, 14, 11, 5, 50]]
diag_sort(mat)

[[5, 17, 4, 1, 52, 7],
 [11, 11, 25, 45, 8, 69],
 [14, 23, 25, 44, 58, 15],
 [22, 27, 31, 36, 50, 66],
 [84, 28, 75, 33, 55, 68]]